### ISSUE TITLE
Update to use `syn` v2.0.0

### ISSUE THREAD

**Issue by bravely-beep** [H2CO3/parsel#2]
Since `syn` v2.0.0 has released, many common crates in the rust ecosystem have switched over to use the new version. This results in `syn` being compiled twice in some of my projects, `parsel` is building `syn` v1 while my other dependencies are building v2. `syn` isn't the fastest crate to compile, so updating to v2 would be beneficial.

**Comment by H2CO3** [comment]
This was easier than expected. [Parsel v0.12.0](https://docs.rs/parsel/0.12.0/parsel/) is now released, and uses `syn` 2.0 for parsing primitives and `deluxe` (instead of `darling`) for its own attribute parsing.
