### ISSUE TITLE
Is it possible to change the symbols for Not or And?

### ISSUE THREAD

**Issue by hardliner66** [H2CO3/parsel#4]
As far as I can tell the macro just knows that a `Not` means `!`, but what if I want something else? What if I want the text "not" or some other symbol?

**Comment by H2CO3** [comment]
Sorry, I don't get what the question is.

> the macro just knows that a `Not` means `!`

I don't understand what you are saying with this. Which macro? (Parsel offers many macros.) And what's `Not`?

Parsel can parse *whatever* you want. If you want to recognize custom keywords, you can use the [`custom_keywords!`](https://docs.rs/parsel/latest/parsel/macro.define_keywords.html) macro to define types that parse them.

**Comment by hardliner66** [comment]
Okay, so when you look at the examples, there it just uses `Not` or `And` and the derive macro, which builds the parser, knows that it should use `!` or `&` respectively for the parser. So lets say I want to use `^` for `Not`, is that possible or does that mean I just have to define my own version of `Not` for that?

Edit:
In the following picture an enum is defined containing a `Not` value, which contains a `parsel::ast::token::Not`.
![image](https://github.com/user-attachments/assets/266780ed-1dd4-4d0b-911a-e1b9ae940988)

My question is, if I want a different symbol for that `Not`, how would I do this?

**Comment by H2CO3** [comment]
That's just [`syn::token::Not`](https://docs.rs/syn/latest/syn/token/index.html). You can replace it with any other symbol, such as `syn::token::Caret`. You can also replace it with anything else that implements `Parse`, as tuples are defined to be parsed field-by-field, in sequence.
